apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-api-deployment
spec:
  replicas: 2  # This tells K8s to always keep 2 copies running!
  selector:
    matchLabels:
      app: mlops-api
  template:
    metadata:
      labels:
        app: mlops-api
    spec:
      containers:
      - name: mlops-api
        image: mlops-api:latest
        imagePullPolicy: Never # Crucial: tells K8s to use the image on your Mac, not look online
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-api-service
spec:
  type: NodePort
  selector:
    app: mlops-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001 # This is the "external" port we will use